# Docker swarm demo for cronicle cluster

# Before you start:
# make sure your docker engine is in swarm mode
# build a local cronicle-edge image: docker build -t cronicle:bundle -f Dockerfile .
# create the external secret once: openssl rand -hex 32 | docker secret create secret_key -

# start cluster:         docker stack deploy --compose-file  Docker/LocalCluster.yaml cron_stack
# check status:          docker stack ps cron_stack
# check logs on error:   docker service logs cron_stack_manager1
# remove cluster:        docker stack rm cron_stack

version: '3.8'
services:
  worker1:
    image: cronicle:bundle
    hostname: worker1
    networks:
      - cw
    deploy:
      replicas: 1
    command: worker
    environment:
      - CRONICLE_secret_key_file=/run/secrets/secret_key
    secrets:
      - source: "secret_key"
        target: "secret_key"
        uid: "0"
        gid: "0"
        mode: 0400

  worker2:
    image: cronicle:bundle
    hostname: worker2
    networks:
      - cw
    deploy:
      replicas: 1
    command: worker
    environment:
      - CRONICLE_secret_key_file=/run/secrets/secret_key
    secrets:
      - source: "secret_key"
        target: "secret_key"
        uid: "0"
        gid: "0"
        mode: 0400
 
  manager1:
    image: cronicle:bundle
    hostname: manager1
    ports: 
      - "3012:3012"
    volumes:
      - cron_drive_fs:/opt/cronicle/data
    networks:
      - cw
    deploy:
      replicas: 1
    command: manager
    environment:
      - CRONICLE_secret_key_file=/run/secrets/secret_key
    secrets:
      - source: "secret_key"
        target: "secret_key"
        uid: "0"
        gid: "0"
        mode: 0400

networks:
  cw:
    driver: overlay
    attachable: true
    
secrets:
  secret_key:
    external: true

volumes:
  cron_drive_fs:

# once manager1 is up and running go to Add Server menu and add worker1 and worker2
