// Cronicle cluster secret resolution and reload protection
// Keeps deployment secrets out of distributable artifacts and fails closed
// when no explicit, durable key has been configured.

const fs = require('fs');

const PLACEHOLDER = 'autogenerated';
const CONFIG_ERROR = 'CRONICLE_SECRET_KEY_INVALID';

function configError(message) {
	const err = new Error(message);
	err.code = CONFIG_ERROR;
	return err;
}

function validateSecret(secret) {
	if ((typeof secret !== 'string') || !secret.trim() || (secret.trim().toLowerCase() === PLACEHOLDER)) {
		throw configError(
			'FATAL ERROR: Configure a non-empty cluster secret using CRONICLE_secret_key, ' +
			'CRONICLE_secret_key_file, or secret_key in the server configuration. ' +
			'The placeholder "autogenerated" is not a valid cluster secret.'
		);
	}
	return secret;
}

function loadSecretFile(env, secretFile, fileSystem) {
	env = env || process.env;
	fileSystem = fileSystem || fs;

	// An explicitly present value (including an empty one) has higher
	// precedence than either file source.  Return the raw string so it can be
	// restored after PixlServer's environment type coercion.
	if (Object.prototype.hasOwnProperty.call(env, 'CRONICLE_secret_key')) {
		return env.CRONICLE_secret_key;
	}

	const explicitFile = !!env.CRONICLE_secret_key_file;
	let contents;
	try {
		contents = fileSystem.readFileSync(secretFile, 'utf8');
	}
	catch (err) {
		if ((err.code === 'ENOENT') && !explicitFile) return;
		if (err.code === 'ENOENT') {
			throw configError('FATAL ERROR: Configured cluster secret file does not exist: ' + secretFile);
		}
		throw configError('FATAL ERROR: Could not read configured cluster secret file ' + secretFile + ': ' + err.message);
	}

	contents = contents.trim();
	env.CRONICLE_secret_key = contents;
	return contents;
}

function configOverridesSecret(server) {
	const overrides = server.configOverrides;
	if (!overrides || (typeof overrides !== 'object')) return false;

	const envPrefix = server.__name.replace(/\W+/g, '_').toUpperCase() + '_';
	return Object.keys(overrides).some(function(key) {
		let configPath = key;
		if (key.startsWith(envPrefix) && (key.length > envPrefix.length)) {
			configPath = key.slice(envPrefix.length).trim()
				.replace(/^_+/, '').replace(/_+$/, '').replace(/__/g, '/');
		}
		return configPath === 'secret_key';
	});
}

function overrideLogTargetsSecret(server, message) {
	const match = String(message).match(/^Applying (?:env )?config override:\s+(.+)$/);
	if (!match) return false;

	const key = match[1];
	const envPrefix = server.__name.replace(/\W+/g, '_').toUpperCase() + '_';
	let configPath = key;
	if (key.startsWith(envPrefix) && (key.length > envPrefix.length)) {
		configPath = key.slice(envPrefix.length).trim()
			.replace(/^_+/, '').replace(/_+$/, '').replace(/__/g, '/');
	}
	return configPath === 'secret_key';
}

function redactSecretArgv(source) {
	const argv = source.slice();
	for (let idx = 0; idx < argv.length - 1; idx++) {
		if (/^-+secret_key$/.test(argv[idx]) && !/^-+/.test(argv[idx + 1])) {
			argv[idx + 1] = '[REDACTED]';
		}
	}
	return argv;
}

function redactSecretConfigLogs(server) {
	const logDebug = server.logDebug;
	server.logDebug = function(level, message, data) {
		if (overrideLogTargetsSecret(server, message)) {
			data = '[REDACTED]';
		}
		else if (/ Starting Up$/.test(String(message)) && data && Array.isArray(data.argv)) {
			data = Object.assign({}, data, { argv: redactSecretArgv(data.argv) });
		}
		else if (/^Spawning background daemon process /.test(String(message)) && Array.isArray(data)) {
			data = redactSecretArgv(data);
		}
		else if (((message === 'Configuration') || (message === 'Configuration was reloaded')) &&
			data && (typeof data === 'object') &&
			Object.prototype.hasOwnProperty.call(data, 'secret_key')) {
			data = Object.assign({}, data, { secret_key: '[REDACTED]' });
		}
		return logDebug.call(this, level, message, data);
	};
}

function guardServerConfig(server, bootstrapSecret) {
	let resolvedSecret;
	let ignoredReloadChange = false;

	function restoreResolvedSecret() {
		if ((resolvedSecret !== undefined) && (server.config.get('secret_key') !== resolvedSecret)) {
			server.config.set('secret_key', resolvedSecret);
			ignoredReloadChange = true;
		}
	}

	// PixlServer emits init after loading JSON, CLI, environment, multiConfig,
	// and config_overrides_file values, but before any component starts.
	server.on('init', function() {
		// PixlServer converts numeric-looking environment values into numbers.
		// Secret values are opaque strings, so restore an explicit env/file value
		// unless the higher-precedence config overrides file supplied the key.
		if ((typeof bootstrapSecret === 'string') && !configOverridesSecret(server)) {
			server.config.set('secret_key', bootstrapSecret);
		}
		resolvedSecret = validateSecret(server.config.get('secret_key'));
		server.config.set('secret_key', resolvedSecret);
		bootstrapSecret = undefined;

		// PixlServer reapplies env and config_overrides_file inside its reload
		// listener, immediately before it logs the resulting configuration.
		// Wrap that step so the frozen key is restored before any such log.
		const applyConfigOverrides = server.applyConfigOverrides;
		server.applyConfigOverrides = function() {
			applyConfigOverrides.apply(this, arguments);
			restoreResolvedSecret();
		};
		redactSecretConfigLogs(server);
	});

	// PixlServer installs its own reload handler before prestart. Registering
	// here makes this listener run after it, so a live config reload cannot
	// rotate the process key underneath encryption and cluster authentication.
	server.on('prestart', function() {
		server.config.on('reload', function() {
			restoreResolvedSecret();
			if (ignoredReloadChange) {
				ignoredReloadChange = false;
				server.logDebug(3, 'Ignoring secret_key change during config reload; restart all cluster nodes to rotate it safely.');
			}
		});
	});
}

module.exports = {
	CONFIG_ERROR,
	guardServerConfig,
	loadSecretFile,
	validateSecret
};
